version: '3.8'
services:

  postgres:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      - DATABASE_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./docker-postgres-init.sql:/docker-entrypoint-initdb.d/docker-postgres-init.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata:
