# Logging
logging:
  level:
    com.rzdp.kobayakawa.core: debug
  file:
    path: app/logs
    name: ${logging.file.path}/${spring.application.name}.log
    max-history: 30
  pattern:
    rolling-file-name: ${logging.file.path}/archived/${spring.application.name}-%d{yyyy-MM-dd}.%i.log

# Spring
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/common,classpath:db/local
    table: schema_history
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
